#!/bin/sh 

bosh -n -u admin -p admin upload release https://bosh.io/d/github.com/cloudfoundry/garden-runc-release
bosh -n -u admin -p admin upload release https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-rootfs-release

# diego release
cd ~/diego-release 
./scripts/generate-bosh-lite-manifests
bosh deployment ~/diego-release/bosh-lite/deployments/diego.yml
bosh -n create release --force
bosh -n -u admin -p admin upload release
bosh -n -u admin -p admin deploy --recreate

# diego as default
cd ~/cf-release
./scripts/generate-bosh-lite-dev-manifest /vagrant/diego-default.yml
bosh deployment bosh-lite/deployments/cf.yml
bosh -n create release --force
bosh -n -u admin -p admin upload release
bosh -n -u admin -p admin deploy